# Generated by Django 3.1.7 on 2021-03-17 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plandiet_app', '0003_auto_20210317_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='diet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plandiet_app.diet'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='exercises',
            field=models.ManyToManyField(default=None, null=True, to='plandiet_app.Exercise'),
        ),
    ]
