# Generated by Django 3.1.7 on 2021-03-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plandiet_app', '0004_auto_20210317_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='exercises',
            field=models.ManyToManyField(null=True, to='plandiet_app.Exercise'),
        ),
    ]
